# Generated by Django 3.2.7 on 2021-10-12 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0001_migracion_inicial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comprobantemodel',
            name='comprobanteCDR',
            field=models.URLField(db_column='cdr', null=True),
        ),
    ]
